commgen/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.conf.urls import url
from myapp.views import home,MyView,LoadCalendar,load_prevnext_calendar
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from schedule.periods import Day, Month, Week, Year
from . import settings
urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # path('', home,name = 'home'),
    # path('ajax/load_prevnext_calendar', load_prevnext_calendar,name = 'load_prevnext_calendar',kwargs={'calendar_slug':'calendar1','period': Month}),
    path('ajax/load_prevnext_calendar', LoadCalendar.as_view(),name = 'load_prevnext_calendar',kwargs={'calendar_slug':'calendar1','period': Month}),
    path('schedule/', include('schedule.urls')),
    path('campaign/', include('myapp.urls')),
    path('login/', auth_views.login, name='login'),
    url(r'^(?P<calendar_slug>[-\w]+)/$', MyView.as_view(), name='home',kwargs={'period': Month}),
    path('logout/', auth_views.logout,{'template_name':'registration/logout.html'}, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    ]
# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('home/', home),
# )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf.urls import url
# from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include
urlpatterns = [
    path('newcampaign/', NewCampaignCreate.as_view(),name='newcampaign'),
    path('search-mailing-list/', SearchMailingList.as_view(),name='search_mailing_list'),
    path('ajax/p1/', load_p1,name='load_p1'),
    path('ajax/p2/', load_p2,name='load_p2'),
    path('ajax/m3/', load_m3,name='load_m3'),
    path('ajax/m4/', load_m4,name='load_m4'),
    path('ajax/m5/', load_m5,name='load_m5'),
    path('ajax/m6/', load_m6,name='load_m6'),
    url(r'^audience/(?P<campaign>[-\w]+)/$', AudienceView.as_view(), name='audience'),
]
# urlpatterns += i18n_patterns(path('',include('myapp.urls')))
# urlpatterns += i18n_patterns(path('home/', home))

schedule/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create,
)

urlpatterns = [
    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),
    url(r'^mycalendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/my_calendar_week.html'),
        name='my_week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),
    url(r'^mycalendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/my_calendar_day.html'),
        name='my_day_calendar',
        kwargs={'period': Day}),

    # url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
    #     CalendarView.as_view(),
    #     name='calendar_home',
    #     ),
    # url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
    #     FullCalendarView.as_view(),
    #     name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

myapp/models.py
from django.db import models
from .utils import increment_campaign_id
from django.urls import reverse


class Campaign(models.Model):
	CAMPAIGN_STATUS = (('Draft','draft'),('Co-author Validation','co_author_validation'),('Approval Waiting','approval_waiting'),('Confirmed','confirmed'),('Scheduled','scheduled'),('Sent','sent'))
	id = models.CharField(primary_key = True,db_column = 'CG_CAMPAIGN_ID',default=increment_campaign_id,max_length=10)
	name = models.CharField(max_length = 255,db_column = 'CG_CAMPAIGN_NAME')
	description = models.TextField(null = True,db_column = 'CG_CAMPAIGN_DESC')
	creation_date = models.DateTimeField(db_column = 'CG_CAMPAIGN_CREATION_DT',auto_now_add=True)
	creator = models.ForeignKey('users.User',db_column = 'CG_CAMPAIGN_CREATOR_CUID',on_delete=models.CASCADE)
	mailing_list = models.ForeignKey('mailing_list.MailingList',null = True,db_column = 'CG_ML_ID',on_delete=models.CASCADE)
	status = models.CharField(max_length = 20,null = True,db_column = 'CG_CAMPAIGN_STATUS')
	clone = models.CharField(max_length = 15,null = True,db_column = 'CG_CAMPAIGN_CLONE_ID')
	template = models.ForeignKey('mailing_templates.Template',null = True,db_column = 'CG_MT_ID',on_delete=models.CASCADE)
	exclusion = models.TextField(null = True,db_column = 'CG_CAMPAIGN_EXC')
	inclusion = models.TextField(null = True,db_column = 'CG_CAMPAIGN_INC')
	campaign_from = models.CharField(null = True,max_length = 255,db_column = 'CG_CAMPAIGN_FROM')
	campaign_cc = models.CharField(null = True,max_length = 255,db_column = 'CG_CAMPAIGN_CC')
	campaign_bcc = models.CharField(null = True,max_length = 255,db_column = 'CG_CAMPAIGN_BCC')
	campaign_body = models.TextField(null = True,db_column = 'CG_CAMPAIGN_BODY')
	recurrence = models.CharField(null = True,max_length=120,db_column = 'CG_CAMPAIGN_REC_ID')

	def get_absolute_url(self):
		print("self...nmae",self.name)
		return reverse('audience',kwargs={"campaign":self.name})

	class Meta:
		db_table = 'CG_Campaign_tbl'


class CampaignAuthor(models.Model):
	campaign = models.ForeignKey('Campaign',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_ID')
	user = models.ForeignKey('users.User',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_USER_ID')
	role = models.ForeignKey('users.Group',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_USER_ROLE')
	flag = models.CharField(max_length = 2,null = True,db_column = 'CG_CAMPAIGN_USER_EDIT_FLG')
	last_updated_date = models.DateTimeField(auto_now = True,db_column = 'CG_CAMPAIGN_USER_LAST_DATE')
	status = models.CharField(max_length = 20,null = True,db_column = 'CG_CAMPAIGN_USER_STATUS')

	class Meta:
		db_table = 'CG_Campaign_author_tbl'

class CampaignReader(models.Model):
	campaign = models.ForeignKey('Campaign',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_ID')
	reader = models.ForeignKey('users.User',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_READER_ID')
	status = models.CharField(max_length = 20,null = True,db_column = 'CG_CAMPAIGN_USER_STATUS')

	class Meta:
		db_table = 'CG_Campaign_reader_tbl'


class CampaignApprover(models.Model):
	ACTION = (('Approve','approve'),('Reject','reject'),('Pending','pending'))
	campaign = models.ForeignKey('Campaign',on_delete = models.CASCADE,db_column = 'CG_CAMPAIGN_ID')
	level = models.CharField(max_length = 2,db_column = 'CG_CAMPAIGN_APV_LVL')
	approver = models.CharField(max_length = 255,db_column = 'CG_CAMPAIGN_APV_NAME')
	cuid = models.CharField(max_length = 2,db_column = 'CG_CAMPAIGN_APV_CUID')
	action = models.CharField(max_length = 50,db_column = 'CG_CAMPAIGN_APV_ACTN')
	date_of_action = models.DateTimeField(db_column = 'CG_CAMPAIGN_APV_ACTNDT')
	comment = models.TextField(null = True,db_column = 'CG_CAMPAIGN_APV_COMMENTS')
	status = models.CharField(max_length = 20,db_column = 'CG_CAMPAIGN_APV_STATUS')

	class Meta:
		db_table = 'CG_Campaign_approver_tbl'


class DepartmentSetup(models.Model):
    source = models.CharField(max_length = 10,db_column = 'CM_STP_SOURCE',null = True,blank=True)
    status = models.CharField(max_length = 50,db_column = 'CM_STP_STATUS',null = True,blank=True)
    department_id = models.CharField(max_length =10 ,db_column = 'CM_STP_DEPTID',null = True,blank=True)
    department_name = models.CharField(max_length = 255 ,db_column = 'CM_STP_DEPTNAME',null = True,blank=True)
    level = models.CharField(max_length = 4,db_column = 'CM_STP_LEVEL',null = True,blank=True)
    m1_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M1_DEPT_ID',null = True,blank=True)
    m1_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M1_DEPT_NAME',null = True,blank=True)
    m2_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M2_DEPT_ID',null = True,blank=True)
    m2_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M2_DEPT_NAME',null = True,blank=True)
    m3_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M3_DEPT_ID',null = True,blank=True)
    m3_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M3_DEPT_NAME',null = True,blank=True)
    m4_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M4_DEPT_ID',null = True,blank=True)
    m4_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M4_DEPT_NAME',null = True,blank=True)
    m5_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M5_DEPT_ID',null = True,blank=True)
    m5_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M5_DEPT_NAME',null = True,blank=True)
    m6_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M6_DEPT_ID',null = True,blank=True)
    m6_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M6_DEPT_NAME',null = True,blank=True)
    m7_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M7_DEPT_ID',null = True,blank=True)
    m7_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M7_DEPT_NAME',null = True,blank=True)
    m8_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M8_DEPT_ID',null = True,blank=True)
    m8_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M8_DEPT_NAME',null = True,blank=True)
    m9_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M9_DEPT_ID',null = True,blank=True)
    m9_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M9_DEPT_NAME',null = True,blank=True)
    m10_department_id = models.CharField(max_length = 10,db_column = 'CM_STP_M10_DEPT_ID',null = True,blank=True)
    m10_department_name = models.CharField(max_length = 255,db_column = 'CM_STP_M10_DEPT_NAME',null = True,blank=True)
    class Meta:
        db_table = 'CM_Department_Setup_tbl'


class LocationSetup(models.Model):
	generic_company = models.CharField(max_length=20,db_column='CM_STP_GEN_COMP',null=True)
	region = models.CharField(max_length=20,db_column='CM_STP_REGION',null=True)
	country = models.CharField(max_length=20,db_column='CM_STP_COUNTRY',null=True)
	location = models.CharField(max_length=20,db_column='CM_STP_LOCATION',null=True)
	status = models.CharField(max_length=20,db_column='CM_STP_STATUS',null=True)

	class Meta:
		db_table = 'CM_Location_Setup_tbl'

myapp/forms.py
from django import forms
from .models import *

class MailingListForm(forms.Form):
    # class Meta:
        # model = Person
        # fields = ('name', 'birthdate', 'country', 'city')

    entity = forms.ModelChoiceField(queryset=DepartmentSetup.objects.all().values('source').distinct())
    p1_department = forms.ModelMultipleChoiceField(queryset=DepartmentSetup.objects.all().values('m1_department_id','m1_department_name').distinct())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['p1_department'].queryset = DepartmentSetup.objects.none()

        if 'source' in self.data:
            try:
                source = int(self.data.get('source'))
                self.fields['m1_department_id'].queryset = DepartmentSetup.objects.filter(source=source).order_by()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
            # self.fields['m1_department_id'].queryset = self.order_by('name')
            # self.fields['p1_department_id'].queryset = self.instance.country.city_set.order_by('name')

templates/myapp/audience.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{{campaign}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
     <div class="navbar-nav" style="margin-left: 30rem">
     	<button type="button" class="btn btn-success" style="margin-left: .1rem">{% trans 'Save as draft' %}</button>
     	<button type="button" class="btn btn-success" style="margin-left: .1rem">{% trans 'Previous' %}</button>
     	<button type="button" class="btn btn-success" style="margin-left: .1rem">{% trans 'Next' %}</button>
     	<button type="button" class="btn btn-success" style="margin-left: .1rem">{% trans 'Cancel' %}</button>
     	<button type="button" class="btn btn-success" style="margin-left: .1rem">{% trans 'Submit' %}</button>
    </div>
  </div>
</nav>
<div class="container">
	<div class="row">
		<div class="col-md-2" style="padding:0; ">
			<ul class="list-group">
			  <li class="list-group-item active">{% trans 'Audience' %}</li>
			  <li class="list-group-item">{% trans 'Mailing List Exclusion' %}/{% trans 'Count' %}</li>
			  <li class="list-group-item">{% trans 'Other' %}/{% trans 'Attachment' %}/ {% trans 'Dynamic Variable' %}</li>
			  <li class="list-group-item">{% trans 'Template' %}</li>
			  <li class="list-group-item">{% trans 'Schedule' %}/{% trans 'Co-Author' %}</li>
			  <li class="list-group-item">{% trans 'Preview' %}</li>
			  <li class="list-group-item">{% trans 'Approval Workflow' %}</li>
			</ul>
		</div>
		<div class="col-md-10">
			<div class="jumbotron" style="border: 1px solid #ddd;border-radius: 30px;margin-top: 1rem">
        <form method="POST" action="{% url 'search_mailing_list' %}">{% csrf_token %}
			  <div class="container">
          <div class="row">
            <input type="text" name="campaign" hidden="" value="{{campaign}}">
          <label>Entity</label>
          <select class="custom-select" id="entity" name="entity">
            <option value="">Select Entity</option>
          {% for source in sources %}
            <option value="{{source.source}}">{{source.source}}</option>
          {% endfor %}
          </select>
        </div>
          <div class="row">
    <div class="col-md-6">
          <label>Department P1</label>
          <select class="custom-select" id="id_p1" name="department_p1" multiple>
          </select>
        </div>
    <div class="col-md-6">
          <label>Department P2</label>
          <select class="custom-select" id="id_p2" multiple>
          </select>
        </div>
      </div>
          <div class="row">
    <div class="col-md-6">
          <label>Department M3</label>
          <select class="custom-select" id="id_m3" multiple>
          </select>
        </div>
    <div class="col-md-6">
          <label>Department M4</label>
          <select class="custom-select" id="id_m4" multiple>
          </select>
        </div>
        </div>
        <div class="row">
    <div class="col-md-6">
          <label>Department M5</label>
          <select class="custom-select" id="id_m5" multiple>
          </select>
        </div>
    <div class="col-md-6">
          <label>Department M6</label>
          <select class="custom-select" id="id_m6" multiple>
          </select>
			  </div>
      </div>
        <div class="row">
          <div class="col-md-6">
            <label>Generic Country</label>
            <select class="custom-select" id="id_generic_company" multiple>
            </select>
          </div>
        <div class="col-md-6">
          <label>Region</label>
          <select class="custom-select" id="id_region" multiple>
          </select>
        </div>
      </div>
      <div class="row">
          <div class="col-md-6">
            <label>Country</label>
            <select class="custom-select" id="id_country" multiple>
            </select>
          </div>
        <div class="col-md-6">
          <label>Location</label>
          <select class="custom-select" id="id_location" multiple>
          </select>
        </div>
      </div>
      <div class="row">
          <div class="col-md-6">
            <label>Status</label>
            <select class="custom-select" id="id_status" multiple>
            </select>
          </div>
        <div class="col-md-6">
          <label>Regular/Temporary Staff</label>
          <select class="custom-select" id="id_staff" multiple>
          </select>
        </div>
      </div>
      <div class="row">
          <div class="col-md-6">
            <label>Manager/Non-Manager</label>
            <select class="custom-select" id="id_manager" name="manager" multiple>
            </select>
          </div>
        <div class="col-md-6">
          <label>Preferred Language</label>
          <select class="custom-select" id="id_preferred_language" name="preferred_language" multiple>
          </select>
        </div>
      </div>
      <div class="row">
          <div class="col-md-6">
            <label>Staff Status</label>
            <select class="custom-select" id="id_staff_status" name="manager" multiple>
            </select>
          </div>
<!--         <div class="col-md-6">
          <label>Preferred Language</label>
          <select class="custom-select" id="id_staff" multiple>
          </select>
        </div> -->
      </div>

    </div>
    <button type="Submit" name="Submit">Search</button>
  </form>
			</div>
		</div>
	</div>
</div>

  <script src="{% static 'js/myapp/audience.js' %}"></script>
{% endblock  %}

templates/myapp/create_new_campaign.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock  %}

templates/myapp/mailing_list_exclusion.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Christmas Email</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
     <div class="navbar-nav" style="margin-left: 30rem">
     	<a href="#" class="btn btn-success" style="margin-left: .1rem">{% trans 'Save as draft' %}</a>
     	<a href="{% url 'audience' %}" class="btn btn-success" style="margin-left: .1rem">{% trans 'Previous' %}</a>
     	<a href="" class="btn btn-success" style="margin-left: .1rem">{% trans 'Next' %}</a>
     	<a href="" class="btn btn-success" style="margin-left: .1rem">{% trans 'Cancel' %}</a>
     	<a href="" class="btn btn-success" style="margin-left: .1rem">{% trans 'Submit' %}</a>
    </div>
  </div>
</nav>
<div class="container">
	<div class="row">
		<div class="col-md-2" style="padding:0; ">
			<ul class="list-group">
			  <li class="list-group-item">{% trans 'Audience' %}</li>
			  <li class="list-group-item active">{% trans 'Mailing List Exclusion' %}/{% trans 'Count' %}</li>
			  <li class="list-group-item">{% trans 'Other' %}/{% trans 'Attachment' %}/ {% trans 'Dynamic Variable' %}</li>
			  <li class="list-group-item">{% trans 'Template' %}</li>
			  <li class="list-group-item">{% trans 'Schedule' %}/{% trans 'Co-Author' %}</li>
			  <li class="list-group-item">{% trans 'Preview' %}</li>
			  <li class="list-group-item">{% trans 'Approval Workflow' %}</li>
			</ul>
		</div>
		<div class="col-md-10">
			<div class="jumbotron" style="border: 1px solid #ddd;border-radius: 30px;margin-top: 1rem">
			  <div class="container">
			    <h1 class="display-4">Fluid jumbotron</h1>
			    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
			  </div>
			</div>
		</div>
	</div>
</div>

{% endblock  %}